config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = List.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save

    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), notice: 'Bookmark was deleted'
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-3">
  <h1>New Bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <div class="form-inputs">
      <%= f.input :comment %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://thumbs.dreamstime.com/z/cinema-film-background-camera-clapperboard-tickets-rolls-glasses-popcorn-lens-reel-film-soda-cinema-film-blue-background-118776533.jpg);">
  <div class="container d-flex justify-content-center">
    <h1>Save any kind of movies</h1>
  </div>
</div>


<div class="container d-flex justify-content-between mt-5">
  <h1>My Lists</h1>
  <%= link_to 'Create a new movie list', new_list_path, class: "btn btn-success" %>
</div>

<div class="row d-flex mt-3">
  <% @lists.each do |list| %>
      <div class="col-4">
        <div class="card-category w-100 mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill if list.photo.attached?%>')">
            <%= link_to list.name, list %>
        </div>
      </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container mt-3">
  <h1>New Restaurant</h1>

  <%= simple_form_for(@list) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
    </div>

    <div class="form-inputs">
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit ,  class: "btn btn-light my-3"%>
    </div>
  <% end %>

  <%= link_to 'Back', root_path, class: "btn btn-primary" %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
  <div class="container d-flex justify-content-center">
    <h1>Save any kind of movies</h1>
  </div>
</div>

<div class="container d-flex justify-content-between mt-5 mb-5">
  <h1><%= @list.name %></h1>
  <%= link_to "Add a new bookmark", new_list_bookmark_path(@list), class: "btn btn-info" %>
</div>

<div class="container mb-5">
  <br><br><strong>Movies:</strong>
  <div class="row d-flex mx-3">
    <% @list.movies.each do |movie| %>
      <div class="col-5 card mt-5 mx-3" style="width: 18rem;">
        <div class="card-body w-100">
          <h5 class="card-title"><%= movie.title %></h5>
          <p class="card-text"><%= movie.overview %></p>
          <% @list.bookmarks.each do |bookmark| %>
            <% if movie.id == bookmark.movie_id %>
              <%= bookmark.comment %>
              <%= link_to "Delete Bookmark", root_path(bookmark), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <br><br><%= link_to "Back to home", root_path, class: "btn btn-primary" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to lists_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "My Lists", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New List", new_list_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>